/*
*  Parameters 
* ----------------
* ENVIRONMENT : Enviroment where tests needs to be run .
* SLACK_CHANNEL : Slack channel where the output is to be posted
* SLACK_TOKEN : Slack bot token for posting messages to slack
* GIT_URL : Git URL of test repo. Eg : https://bitbucket.org/keyvaluesoftwaresystems/test.git
* GIT_CREDENTIALS : Git credentials id in Jenkins
* GIT_BRANCH : Branch where automation scripts are checked in
* NODE_JS : Node Js installation name
* BROWSER : Browser against which tests needs to be run
* TAGS : Tags for choosing features to be run
* SLACK_MSG_TITLE : Message title to be displayed in slack
* CUSTOM_MESSAGE : Custom message to be displayed to slack [Optional]
*/

pipeline {
    agent any
      // Various parameters used in this script
	// Uncommenting this will override the parameters set from jenkins UI
	/*
      parameters {
         choice(name: 'ENVIRONMENT', choices: ['dev','stg','prod'], description: 'Enviroment where tests needs to be run .')
         choice(name: 'SLACK_CHANNEL', choices: ['@sajeer','#invalid-123','#test-repo'], description: 'Slack channel where the output is to be posted')
         string(name: 'GIT_BRANCH', defaultValue: 'dev', description: 'Branch where automation scripts are checked in')
         choice(name: 'BROWSER', choices: ['chrome','firefox','edge'], description: 'Browser against which tests needs to be run')
         string(name: 'TAGS', defaultValue: '@Login', description: 'Tags for choosing features to be run')
         string(name: 'CUSTOM_MESSAGE', defaultValue: '', description: 'Custom message to be posted to slack [ Optional]')
 }*/
    
    // Environment variables used in the script.
    environment {
        GIT_URL = 'git@bitbucket.org:keyvaluesoftwaresystems/automation_typescript_playwright.git'
        SLACK_TOKEN =  credentials('SLACK_TOKEN')
        GIT_CREDENTIALS = 'qa-kv-ssh'
        NODE_JS = 'node 18'
        SLACK_MSG_TITLE = 'UI Automation Test Result'
		HEADLESSMODE ='true'
		BROWSER="${params.BROWSER}"
    }

    options {
        disableConcurrentBuilds()
        skipStagesAfterUnstable()
        timestamps()
        retry(0)
        timeout(time: 180, unit: 'MINUTES')
        skipDefaultCheckout()
    }

    tools {nodejs "${env.NODE_JS}"}

    stages {
	/*
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
		*/
        stage('Check out') {
            steps {
                echo 'Checking out latest test scripts'
                git branch: "${TEST_BRANCH}", credentialsId: "${env.GIT_CREDENTIALS}", url: "${env.GIT_URL}"
            }
        }
		
        stage('Environment Setup') {
            steps {
                sh label: 'Pre-Build Setup', script: """
                rm -rf reports
                npx playwright install
                npm install
                """
            }
        }
        
        stage('Test Case Execution') {
            steps {
				script {
					if (params.TAGS) 
                		sh label: 'Executing test suite', returnStatus: true, script: "npx cucumber-js --tags '${params.TAGS}'"
					else
						sh label: 'Executing test suite', returnStatus: true, script: "npx cucumber-js"
				}	
            }
        }
    }

    post {
        always {
            echo 'Archiving Artifacts'
            echo 'Publishing results'
            //allure results: [[path: '**/allure-report']]
            archiveArtifacts allowEmptyArchive: true, artifacts: 'reports/cucumber-report.json', fingerprint: true, followSymlinks: false
            cucumber buildStatus: 'null',  failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: 'reports/cucumber-report.json', pendingStepsNumber: -1, skipEmptyJSONFiles: true, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1
			publishHTML([allowMissing: true, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'reports', reportFiles: 'report.html', reportName: 'HtmlReport', reportTitles: '', useWrapperFileDirectly: true])
           script {
                currentBuild.description = "${ENVIRONMENT} - ${TAGS}"
			   	if (params.CUSTOM_MSG) 
				    sh label: 'posting result to slack', returnStatus: true, script: 'python3 jenkins/cucumberToSlack.py -u $BUILD_URL -t $SLACK_TOKEN -s "$SLACK_CHANNEL" -n "$CUSTOM_MSG" -r "$SLACK_MSG_TITLE" -l reports/cucumber-report.json' 
				else
					sh label: 'posting result to slack', returnStatus: true, script: 'python3 jenkins/cucumberToSlack.py -u $BUILD_URL -t $SLACK_TOKEN -s "$SLACK_CHANNEL" -r "$SLACK_MSG_TITLE" -l reports/cucumber-report.json'
		   }
        }
    }
}